[docker]
# Configs have a mapping between the Docker image to use and the capabilities that need to be matched to
# start a container with the given image.
configs = [
    "selenium/standalone-firefox:4.1.2-20220131", "{\"browserName\": \"firefox\"}",
    "selenium/standalone-chrome:4.1.2-20220131", "{\"browserName\": \"chrome\"}",
    "selenium/standalone-edge:4.1.2-20220131", "{\"browserName\": \"MicrosoftEdge\"}"
    ]

# URL for connecting to the docker daemon
# Linux could use --net=host in the `docker run` instruction or 172.17.0.1 in the URI below.
url = "172.17.0.1"
# Docker image used for video recording
video-image = "selenium/video:ffmpeg-4.3.1-20220131"

