version: '3'
x-logging: 
  &default-logging
  driver: json-file
  options:
    max-file: '3'
    max-size: 15m

services:
  crawler_db:
    container_name: crawler_db
    image: postgres:14.5-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./crawler_db_volume/:/var/lib/postgresql/data
    logging: *default-logging
    networks:
      - crawler_network

  crawler_api:
    container_name: crawler_api
    build: .
    depends_on:
      - crawler_db
    env_file:
      - .env
    volumes:
      - ./static:/app/crawler/static
    ports:
      - 127.0.0.1:8205:80
    restart: unless-stopped
    logging: *default-logging
    networks:
      - crawler_network

  crawler_worker:
    container_name: crawler_worker
    build: .
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "worker", "-l", "info", "--pidfile=", "--concurrency=1"]
    env_file:
      - .env
    depends_on:
      - crawler_db
      - crawler_redis
    volumes:
      - .:/app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - crawler_network

  crawler_beat:
    container_name: crawler_beat
    build: .
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "beat", "-l", "info", "--pidfile="]
    env_file:
      - .env
    depends_on:
      - crawler_db
      - crawler_redis
    volumes:
      - .:/app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - crawler_network

  crawler_redis:
    container_name : crawler-redis
    image: redis:6.2
    restart: unless-stopped
    volumes:
      - ./redis_volume_pro:/data
    logging: *default-logging
    networks:
      - crawler_network

  crawler_node_docker:
    image: selenium/node-firefox:4.9.0-20230421
    container_name: crawler_node_docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets:/opt/selenium/assets
    depends_on:
      - crawler_selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=crawler-selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    shm_size: 2g
    restart: unless-stopped
    networks:
      - crawler_network

  crawler_selenium_hub:
    image: selenium/hub:4.9.0-20230421
    container_name: crawler-selenium-hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - crawler_network

networks:
  crawler_network:
