version: '3.8'
x-logging: 
  &default-logging
  driver: json-file
  options:
    max-file: '3'
    max-size: 15m

services:
  crawler_db:
    container_name: crawler_db
    image: postgres:14.5-alpine
    env_file:
      - .env
    volumes:
      - ./crawler_db_volume/:/var/lib/postgresql/data
    logging: *default-logging
    networks:
      - crawler_network
    restart: unless-stopped

  crawler_api:
    container_name: crawler_api
    build: .
    depends_on:
      - crawler_db
    env_file:
      - .env
    volumes:
      - ./static:/app/crawler/static
      - ./logs:/app/crawler/logs
    ports:
      - 127.0.0.1:8205:80
    logging: *default-logging
    networks:
      - crawler_network
    restart: unless-stopped

  crawler_worker:
    build: .
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "worker", "-l", "info", "--pidfile=", "--concurrency=1"]
    env_file:
      - .env
    depends_on:
      - crawler_db
      - crawler_redis
    volumes:
      - .:/app
      - ./logs:/app/crawler/logs
    logging: *default-logging
    networks:
      - crawler_network
    restart: unless-stopped

  crawler_beat:
    container_name: crawler_beat
    build: .
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "beat", "-l", "info", "--pidfile="]
    env_file:
      - .env
    depends_on:
      - crawler_db
      - crawler_redis
    volumes:
      - .:/app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - crawler_network

  crawler_redis:
    container_name : crawler-redis
    image: redis:6.2
    volumes:
      - ./redis_volume_pro:/data
    logging: *default-logging
    networks:
      - crawler_network
    restart: unless-stopped

  crawler_node_docker:
    image: selenium/node-firefox:4.26.0-20241101
    container_name: crawler_node_docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./assets:/opt/selenium/assets
    depends_on:
      - crawler_selenium_hub
    environment:
      - SE_EVENT_BUS_HOST=crawler-selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - JAVA_OPTS=-Dotel.traces.exporter=none
    shm_size: 2g
    networks:
      - crawler_network
    restart: unless-stopped

  crawler_selenium_hub:
    image: selenium/hub:4.26.0-20241101
    container_name: crawler-selenium-hub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - crawler_network
    environment:
      - JAVA_OPTS=-Dotel.traces.exporter=none
    restart: unless-stopped

networks:
  crawler_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 # necessary for socks proxy access via ufw to have a fixed ip range
