version: '3.4'

services:
  crawler_db:
    container_name: crawler_db
    image: mdillon/postgis:11
    restart: unless-stopped
    volumes:
      - ./crawler_db_volume/:/var/lib/postgresql/data

  crawler_api:
    container_name: crawler_api
    build: .
    depends_on:
      - crawler_db
    env_file:
      - .env
    volumes:
      - ./static:/app/crawler/static
    ports:
      - "127.0.0.1:8205:80"
    restart: unless-stopped

  crawler_celery:
    container_name: crawler_celery
    build: .
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "worker", "-l", "info"]
    env_file:
      - .env
    depends_on:
      - crawler_db
      - crawler_redis
    restart: unless-stopped

  crawler_beat:
    container_name: crawler_beat
    build: .
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "beat", "-l", "info", "--pidfile="]
    env_file:
      - .env
    depends_on:
      - crawler_db
      - crawler_redis
    volumes:
      - ./log/beat:/var/log/app
    logging:
      driver: none
    restart: unless-stopped

  crawler_redis:
    container_name : crawler_redis
    image: redis:6.2
    logging:
      driver: none
    restart: unless-stopped

  crawler_chrome:
    image: selenium/standalone-chrome
    container_name: crawler_chrome
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: 15m
    restart: unless-stopped
