# Generated by Django 3.2.9 on 2022-01-21 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='network',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AddField(
            model_name='post',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='social.publisher'),
        ),
    ]
