# Generated by Django 3.2.9 on 2022-01-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20220121_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publisher',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
