# Generated by Django 3.2.9 on 2022-01-06 09:35

import agency.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=agency.utils.report_image_path),
        ),
    ]
