# Generated by Django 3.2.9 on 2022-01-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=300, null=True),
        ),
    ]
