# Generated by Django 3.2.9 on 2022-02-06 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_alter_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='alexa_global_rank',
        ),
    ]
