# Generated by Django 4.1 on 2022-10-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_remove_agency_alexa_global_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
            ],
        ),
    ]
