# Generated by Django 4.1 on 2022-11-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_dblogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
