# Generated by Django 4.1 on 2022-11-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
