# Generated by Django 4.1 on 2023-12-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_agency_load_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='load_timeout',
            field=models.PositiveIntegerField(default=5, help_text='how many seconds to wait for page to load'),
        ),
    ]
