# Generated by Django 4.1 on 2024-02-11 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_messagetemplate'),
        ('agency', '0018_alter_agency_load_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.messagetemplate'),
        ),
    ]
