# Generated by Django 4.1 on 2024-10-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_page_message_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='message_code',
            field=models.TextField(default=None, help_text='message=data["link"] or data["iv_link"]', null=True),
        ),
    ]
