# Generated by Django 4.1 on 2024-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_alter_page_message_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='scroll',
            field=models.PositiveIntegerField(default=0, help_text='how many times to scroll'),
        ),
        migrations.AlterField(
            model_name='page',
            name='message_code',
            field=models.TextField(blank=True, default=None, help_text='message=data["link"] or data["iv_link"]', null=True),
        ),
    ]
