# Generated by Django 4.1 on 2025-01-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_page_filtering_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'Off Time',
                'verbose_name_plural': 'Off Times',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='page',
            name='off_times',
            field=models.ManyToManyField(blank=True, related_name='pages', to='agency.offtime'),
        ),
    ]
