# Generated by Django 4.1 on 2025-01-12 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_offtime_created_at_offtime_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlScheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agency.page')),
            ],
            options={
                'verbose_name': 'Crawl Scheduling',
                'verbose_name_plural': 'Crawl Scheduling',
                'ordering': ['start_time'],
            },
        ),
    ]
