# Generated by Django 4.1 on 2025-01-12 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0026_day_crawlscheduling'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawlscheduling',
            options={},
        ),
        migrations.RemoveField(
            model_name='crawlscheduling',
            name='start_time',
        ),
    ]
