# Generated by Django 4.1 on 2025-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_day_created_at_day_deleted_at_day_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlscheduling',
            name='days',
            field=models.CharField(help_text='MON,TUE,WED,THU,FRI,SAT,SUN. You should use comma to separate.', max_length=50),
        ),
        migrations.AlterField(
            model_name='crawlscheduling',
            name='start_times',
            field=models.TextField(help_text='e.g., 08:00,12:00,18:00. You should use comma to separate.'),
        ),
    ]
