# Generated by Django 3.0.5 on 2020-04-17 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('country', models.CharField(default='NA', max_length=20)),
                ('website', models.CharField(max_length=100)),
                ('crawl_headers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_crawl', models.DateTimeField(null=True)),
                ('last_crawl_duration', models.DateTimeField(null=True)),
                ('last_crawl_status', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agency.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPageStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('crawl_interval', models.IntegerField(default=12)),
                ('last_crawl', models.DateTimeField(editable=False, null=True)),
                ('news_links_structure', django.contrib.postgres.fields.jsonb.JSONField()),
                ('news_meta_structure', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agency.Agency')),
            ],
        ),
    ]
