# Generated by Django 3.0.5 on 2020-04-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypagestructure',
            name='last_crawl',
            field=models.DateTimeField(null=True),
        ),
    ]
