# Generated by Django 3.0.5 on 2020-04-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlreport',
            name='last_crawl',
        ),
        migrations.RemoveField(
            model_name='crawlreport',
            name='last_crawl_duration',
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='fetched_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='new_links',
            field=models.IntegerField(default=0),
        ),
    ]
