# Generated by Django 3.0.5 on 2020-04-19 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_auto_20200419_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlreport',
            name='agency',
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='agency.AgencyPageStructure'),
            preserve_default=False,
        ),
    ]
