# Generated by Django 3.0.5 on 2020-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_agencypagestructure_last_crawl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypagestructure',
            name='last_crawl',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
