# Generated by Django 3.0.5 on 2021-10-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20211029_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='link_keep_days',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='how many days to keep the links of crawled page in redis', null=True),
        ),
    ]
