# Generated by Django 3.0.5 on 2020-05-25 04:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20200415_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='crawlreport',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='crawlreport',
            name='last_crawl',
        ),
        migrations.RemoveField(
            model_name='crawlreport',
            name='last_crawl_duration',
        ),
        migrations.RemoveField(
            model_name='crawlreport',
            name='last_crawl_status',
        ),
        migrations.AddField(
            model_name='agency',
            name='alexa_global_rank',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='country',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='fetched_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='new_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='page',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='agency.AgencyPageStructure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlreport',
            name='status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='crawl_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agencypagestructure',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='agencypagestructure',
            name='last_crawl',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='agencypagestructure',
            name='news_links_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='agencypagestructure',
            name='news_meta_structure',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='agencypagestructure',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
