# Generated by Django 3.0.5 on 2021-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_agency_link_keep_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='last_crawl_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
