# Generated by Django 3.0.5 on 2020-04-19 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20200419_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypagestructure',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='crawlreport',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.AgencyPageStructure'),
        ),
    ]
