# Generated by Django 3.0.5 on 2020-04-24 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20200419_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypagestructure',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='agency.Agency'),
        ),
        migrations.AlterField(
            model_name='crawlreport',
            name='last_crawl_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='crawlreport',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='agency.AgencyPageStructure'),
        ),
    ]
