# Generated by Django 3.2.9 on 2021-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_page_last_crawl_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='crawl_headers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='cookie',
            name='key_values',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='structure',
            name='news_links_structure',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='structure',
            name='news_meta_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
