# Generated by Django 3.0.5 on 2020-05-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_auto_20200528_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypagestructure',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
