# Generated by Django 3.0.5 on 2020-05-28 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200528_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencypagestructure',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
