# Generated by Django 3.0.5 on 2020-04-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_auto_20200424_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlreport',
            old_name='last_crawl_status',
            new_name='status',
        ),
    ]
