# Generated by Django 3.0.5 on 2020-05-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_auto_20200424_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='alexa_global_rank',
            field=models.IntegerField(default=12),
        ),
    ]
