# Generated by Django 3.0.5 on 2020-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_auto_20200628_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencypagestructure',
            name='fetch_content',
            field=models.BooleanField(default=1),
        ),
    ]
