# Generated by Django 3.0.5 on 2020-05-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_auto_20200508_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='alexa_global_rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
