# Generated by Django 3.0.5 on 2020-08-28 12:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_agencypagestructure_fetch_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_links_structure', django.contrib.postgres.fields.jsonb.JSONField()),
                ('news_meta_structure', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='agencypagestructure',
            name='page_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agency.PageStructure'),
        ),
    ]
