# Generated by Django 3.0.5 on 2020-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20200828_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestructure',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
