# Generated by Django 3.0.5 on 2020-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_auto_20200508_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='website',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='agencypagestructure',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
