# Generated by Django 3.0.5 on 2020-08-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_pagestructure_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgencyPageStructure',
            new_name='Page',
        ),
    ]
