# Generated by Django 3.0.5 on 2020-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20200618_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlreport',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
