# Generated by Django 3.0.5 on 2020-08-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_auto_20200828_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_structure',
            new_name='structure',
        ),
    ]
