# Generated by Django 3.0.5 on 2020-06-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_crawlreport_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=70)),
                ('value', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
