# Generated by Django 3.0.5 on 2020-08-28 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_auto_20200828_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='news_links_structure',
        ),
        migrations.RemoveField(
            model_name='page',
            name='news_meta_structure',
        ),
    ]
