# Generated by Django 3.0.5 on 2020-08-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_auto_20200828_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='telegram_channel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
