# Generated by Django 3.0.5 on 2020-08-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_auto_20200828_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='message_code',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
