# Generated by Django 3.0.5 on 2020-08-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0018_page_message_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='iv_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
