# Generated by Django 3.0.5 on 2020-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0019_page_iv_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='take_picture',
            field=models.BooleanField(default=False),
        ),
    ]
