# Generated by Django 3.0.5 on 2020-08-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0020_page_take_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlreport',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/crawler'),
        ),
    ]
