# Generated by Django 3.0.5 on 2020-08-29 12:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0021_crawlreport_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlreport',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/static/crawler'), upload_to=''),
        ),
    ]
