# Generated by Django 3.0.5 on 2020-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0022_auto_20200829_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagestructure',
            name='news_links_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crawlreport',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='.static/crawler/static'),
        ),
    ]
