# Generated by Django 3.0.5 on 2020-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0023_auto_20200829_1932'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageStructure',
            new_name='Structure',
        ),
        migrations.AlterField(
            model_name='page',
            name='message_code',
            field=models.TextField(blank=True, default=None, help_text='message=data["link"] or data["iv_link"]', null=True),
        ),
    ]
