# Generated by Django 3.0.5 on 2020-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0025_auto_20200830_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='news_meta_code',
            field=models.TextField(null=True),
        ),
    ]
