# Generated by Django 3.0.5 on 2020-09-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0028_auto_20200904_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='links_sleep',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='load_sleep',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
