# Generated by Django 3.0.5 on 2020-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0029_auto_20200907_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='crawl_interval',
            field=models.PositiveIntegerField(default=60, help_text='minute'),
        ),
        migrations.AlterField(
            model_name='page',
            name='links_sleep',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='page',
            name='load_sleep',
            field=models.PositiveIntegerField(blank=True, default=4),
        ),
    ]
