# Generated by Django 3.0.5 on 2020-09-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0030_auto_20200907_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='links_sleep',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='all links sleep'),
        ),
        migrations.AlterField(
            model_name='page',
            name='load_sleep',
            field=models.PositiveIntegerField(blank=True, default=4, help_text='each link sleep'),
        ),
    ]
