# Generated by Django 3.0.5 on 2020-09-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0031_auto_20200907_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='telegram_channel',
            field=models.CharField(blank=True, help_text='like: @jobinja', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='structure',
            name='news_links_code',
            field=models.TextField(blank=True, help_text='like: for el in elements: try: links.append(el["href"]) except: continue', null=True),
        ),
    ]
