# Generated by Django 3.0.5 on 2020-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0033_auto_20201016_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
