# Generated by Django 3.0.5 on 2020-11-27 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0034_cookie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookie',
            name='name',
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agency.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
