# Generated by Django 3.0.5 on 2020-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0039_auto_20201127_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='error',
            field=models.TextField(null=True),
        ),
    ]
