# Generated by Django 3.0.5 on 2020-11-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0040_log_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
