name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Check formatting with black
        run: |
          black --check .

  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: check_formatting
    steps:
      - uses: actions/checkout@v1
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.IP}}
          port: ${{secrets.PORT}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          script: >
            cd ${{secrets.PROJECT_PATH}} 
            && git pull 
            && docker-compose -f docker-compose-pro.yml up -d --build
